name=MyMIDI
version=1.0.0
author=Mattah
maintainer=Mattah <mattah@gmail.com>
sentence=MyMIDI is a concise library focused on abstracting certain MIDI protocol communications.
paragraph=Through this library you can use MIDI output from Arduino to connect with other devices to send MIDI messages and communicate certains actions to manipulate virtual instruments.
category=Communication
url=https://github.com/Mattaah/my-midi
architectures=*
includes=MyMIDI.h